# Generated by Django 4.0.6 on 2022-09-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('battlefield_role', models.CharField(choices=[('commander', 'Командир'), ('troops', 'Отряд'), ('elite', 'Элита'), ('fast_attack', 'Отраяды быстрой атаки'), ('heavy_support', 'Тяжелая поддержка'), ('flyers', 'Летающая техника'), ('dedicated Transport', 'Выделеная техника'), ('lords of War', 'Владыки войны')], max_length=100)),
                ('power_rating', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
                ('movement', models.CharField(blank=True, max_length=100)),
                ('weapon_skill', models.CharField(blank=True, max_length=100)),
                ('ballistic_skill', models.CharField(blank=True, max_length=100)),
                ('streath', models.CharField(blank=True, max_length=100)),
                ('tenesity', models.CharField(blank=True, max_length=100)),
                ('wd', models.CharField(blank=True, max_length=100)),
                ('leader', models.CharField(blank=True, max_length=100)),
                ('attack', models.CharField(blank=True, max_length=100)),
                ('spas_roll', models.CharField(blank=True, max_length=100)),
                ('unit_composition', models.CharField(blank=True, max_length=100)),
                ('wargear', models.TextField(blank=True, max_length=100)),
                ('abilities', models.TextField(blank=True, max_length=100)),
                ('faction_keywords', models.TextField(blank=True, max_length=100)),
                ('keywors', models.TextField(blank=True, max_length=100)),
                ('weapons', models.TextField(blank=True, max_length=100)),
                ('profile', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('armor_penetration', models.CharField(blank=True, max_length=100)),
                ('damage', models.CharField(blank=True, max_length=100)),
                ('abilities', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(limit_choices_to={'battlefield_role': 'commander'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chars', related_query_name='char', to='wh_info.character')),
                ('dedicated_transport', models.ForeignKey(limit_choices_to={'battlefield_role': 'dedicated_transport'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_transport', related_query_name='dedicated_transport', to='wh_info.character')),
                ('elite', models.ForeignKey(limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elites', related_query_name='elite', to='wh_info.character')),
                ('fast_attack', models.ForeignKey(limit_choices_to={'battlefield_role': 'fast_attack'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fast_attacks', related_query_name='fast_attack', to='wh_info.character')),
                ('flyers', models.ForeignKey(limit_choices_to={'battlefield_role': 'flyers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyers', related_query_name='flyers', to='wh_info.character')),
                ('heavy_support', models.ForeignKey(limit_choices_to={'battlefield_role': 'heavy_support'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heavy_supports', related_query_name='heavy_support', to='wh_info.character')),
                ('lords_of_war', models.ForeignKey(limit_choices_to={'battlefield_role': 'lords_of_war'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lords_of_war', related_query_name='lords_of_war', to='wh_info.character')),
                ('troops', models.ForeignKey(limit_choices_to={'battlefield_role': 'troops'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troops', related_query_name='troop', to='wh_info.character')),
            ],
        ),
    ]
