# Generated by Django 4.0.6 on 2022-10-11 16:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('battlefield_role', models.CharField(choices=[('commander', 'Командир'), ('troops', 'Отряд'), ('elite', 'Элита'), ('fast_attack', 'Отраяды быстрой атаки'), ('heavy_support', 'Тяжелая поддержка'), ('flyers', 'Летающая техника'), ('dedicated Transport', 'Выделеная техника'), ('lords of War', 'Владыки войны')], max_length=100)),
                ('power_rating', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
                ('movement', models.CharField(blank=True, max_length=100)),
                ('weapon_skill', models.CharField(blank=True, max_length=100)),
                ('ballistic_skill', models.CharField(blank=True, max_length=100)),
                ('streath', models.CharField(blank=True, max_length=100)),
                ('tenesity', models.CharField(blank=True, max_length=100)),
                ('wd', models.CharField(blank=True, max_length=100)),
                ('leader', models.CharField(blank=True, max_length=100)),
                ('attack', models.CharField(blank=True, max_length=100)),
                ('spas_roll', models.CharField(blank=True, max_length=100)),
                ('view', models.CharField(blank=True, max_length=100)),
                ('unit_composition', models.CharField(blank=True, max_length=100)),
                ('wargear', models.TextField(blank=True, max_length=100)),
                ('abilities', models.TextField(blank=True, max_length=100)),
                ('faction_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None)),
                ('keywors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None)),
                ('weapons', models.TextField(blank=True, max_length=100)),
                ('profile', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MinRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com1', models.ForeignKey(limit_choices_to={'battlefield_role': 'commander'}, on_delete=django.db.models.deletion.CASCADE, related_name='com1', to='wh_info.character')),
                ('com2', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'commander'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com2', to='wh_info.character')),
                ('elite1', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite1', to='wh_info.character')),
                ('elite2', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite2', to='wh_info.character')),
                ('fast_attack1', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'fast_attack'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fast_attack1', to='wh_info.character')),
                ('fast_attack2', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'fast_attack'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fast_attack2', to='wh_info.character')),
                ('flyers1', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'flyers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyers1', to='wh_info.character')),
                ('flyers2', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'flyers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyers2', to='wh_info.character')),
                ('heavy_support1', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'heavy_support'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heavy_support1', to='wh_info.character')),
                ('heavy_support2', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'heavy_support'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heavy_support2', to='wh_info.character')),
                ('tro1', models.ForeignKey(limit_choices_to={'battlefield_role': 'troops'}, on_delete=django.db.models.deletion.CASCADE, related_name='tro1', to='wh_info.character')),
                ('tro2', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'troops'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tro2', to='wh_info.character')),
                ('tro3', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'troops'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tro3', to='wh_info.character')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('armor_penetration', models.CharField(blank=True, max_length=100)),
                ('damage', models.CharField(blank=True, max_length=100)),
                ('abilities', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('character', models.ManyToManyField(limit_choices_to={'battlefield_role': 'commander'}, related_name='chars', to='wh_info.character')),
                ('dedicated_transport', models.ManyToManyField(limit_choices_to={'battlefield_role': 'dedicated Transport'}, related_name='dedicated_transport', to='wh_info.character')),
                ('elite', models.ManyToManyField(limit_choices_to={'battlefield_role': 'elite'}, related_name='elites', to='wh_info.character')),
                ('fast_attack', models.ManyToManyField(limit_choices_to={'battlefield_role': 'fast_attack'}, related_name='fast_attacks', to='wh_info.character')),
                ('flyers', models.ManyToManyField(limit_choices_to={'battlefield_role': 'flyers'}, related_name='flyers', to='wh_info.character')),
                ('heavy_support', models.ManyToManyField(limit_choices_to={'battlefield_role': 'heavy_support'}, related_name='heavy_supports', to='wh_info.character')),
                ('lords_of_war', models.ManyToManyField(limit_choices_to={'battlefield_role': 'lords of War'}, related_name='lords_of_war', to='wh_info.character')),
                ('troops', models.ManyToManyField(limit_choices_to={'battlefield_role': 'troops'}, related_name='troops', to='wh_info.character')),
            ],
        ),
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('minroster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wh_info.minroster')),
                ('com3', models.ForeignKey(limit_choices_to={'battlefield_role': 'commander'}, on_delete=django.db.models.deletion.CASCADE, related_name='com3', to='wh_info.character')),
                ('elite3', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite3', to='wh_info.character')),
                ('elite4', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite4', to='wh_info.character')),
                ('elite5', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite5', to='wh_info.character')),
                ('elite6', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite6', to='wh_info.character')),
                ('fast_attack3', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'fast_attack'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fast_attack3', to='wh_info.character')),
                ('heavy_support3', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'heavy_support'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heavy_support3', to='wh_info.character')),
                ('tro4', models.ForeignKey(limit_choices_to={'battlefield_role': 'troops'}, on_delete=django.db.models.deletion.CASCADE, related_name='tro4', to='wh_info.character')),
                ('tro5', models.ForeignKey(limit_choices_to={'battlefield_role': 'troops'}, on_delete=django.db.models.deletion.CASCADE, related_name='tro5', to='wh_info.character')),
                ('tro6', models.ForeignKey(blank=True, limit_choices_to={'battlefield_role': 'troops'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tro6', to='wh_info.character')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('wh_info.minroster',),
        ),
    ]
