# Generated by Django 4.0.6 on 2022-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='faction_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
