# Generated by Django 4.0.6 on 2022-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='character',
        ),
        migrations.AddField(
            model_name='roster',
            name='character',
            field=models.ManyToManyField(related_name='chars', related_query_name=(), to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='dedicated_transport',
        ),
        migrations.AddField(
            model_name='roster',
            name='dedicated_transport',
            field=models.ManyToManyField(related_name='dedicated_transport', to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='elite',
        ),
        migrations.AddField(
            model_name='roster',
            name='elite',
            field=models.ManyToManyField(related_name='elites', to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='fast_attack',
        ),
        migrations.AddField(
            model_name='roster',
            name='fast_attack',
            field=models.ManyToManyField(related_name='fast_attacks', to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='flyers',
        ),
        migrations.AddField(
            model_name='roster',
            name='flyers',
            field=models.ManyToManyField(related_name='flyers', to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='heavy_support',
        ),
        migrations.AddField(
            model_name='roster',
            name='heavy_support',
            field=models.ManyToManyField(related_name='heavy_supports', to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='lords_of_war',
        ),
        migrations.AddField(
            model_name='roster',
            name='lords_of_war',
            field=models.ManyToManyField(related_name='lords_of_war', to='wh_info.character'),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='troops',
        ),
        migrations.AddField(
            model_name='roster',
            name='troops',
            field=models.ManyToManyField(related_name='troops', to='wh_info.character'),
        ),
    ]
