# Generated by Django 4.0.6 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0002_weapon_character_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='battlefield_role',
            field=models.CharField(choices=[('character', 'Персонаж'), ('troops', 'Отряд'), ('elite', 'Элита'), ('fast_attack', 'Отраяды быстрой атаки'), ('heavy_support', 'Тяжелая поддержка')], max_length=100),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ManyToManyField(to='wh_info.character')),
            ],
        ),
    ]
