# Generated by Django 4.0.6 on 2022-10-18 15:11

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0003_alter_character_keywors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='faction_keywords',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
    ]
