# Generated by Django 4.0.6 on 2022-09-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0003_alter_character_battlefield_role_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='troops',
            field=models.ForeignKey(limit_choices_to={'battlefield_role': 'troops'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troops', related_query_name='troop', to='wh_info.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='battlefield_role',
            field=models.CharField(choices=[('commander', 'Командир'), ('troops', 'Отряд'), ('elite', 'Элита'), ('fast_attack', 'Отраяды быстрой атаки'), ('heavy_support', 'Тяжелая поддержка')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='roster',
            name='character',
        ),
        migrations.AddField(
            model_name='roster',
            name='character',
            field=models.ForeignKey(limit_choices_to={'battlefield_role': 'commander'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chars', related_query_name='char', to='wh_info.character'),
        ),
    ]
