# Generated by Django 4.0.6 on 2022-09-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0004_roster_troops_alter_character_battlefield_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='elite',
            field=models.ForeignKey(limit_choices_to={'battlefield_role': 'elite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elites', related_query_name='elite', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='roster',
            name='fast_attack',
            field=models.ForeignKey(limit_choices_to={'battlefield_role': 'fast_attack'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fast_attacks', related_query_name='fast_attack', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='roster',
            name='heavy_support',
            field=models.ForeignKey(limit_choices_to={'battlefield_role': 'heavy_support'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heavy_supports', related_query_name='heavy_support', to='wh_info.character'),
        ),
    ]
