# Generated by Django 4.0.6 on 2022-10-18 15:16

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0004_alter_character_faction_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True, max_length=300), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='wargear',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), blank=True, size=None),
        ),
    ]
