# Generated by Django 4.0.6 on 2022-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0005_alter_character_abilities_alter_character_wargear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minroster',
            name='com1',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='com2',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='elite1',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='elite2',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='fast_attack1',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='fast_attack2',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='flyers1',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='flyers2',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='heavy_support1',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='heavy_support2',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='tro1',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='tro2',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='tro3',
        ),
        migrations.AddField(
            model_name='minroster',
            name='commanders',
            field=models.ManyToManyField(limit_choices_to={'battlefield_role': 'commander'}, related_name='commander', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='minroster',
            name='elites',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'elite'}, related_name='elite', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='minroster',
            name='fast_attacks',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'fast_attack'}, related_name='fast_attack', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='minroster',
            name='flyers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'flyers'}, related_name='flyer', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='minroster',
            name='heavy_supports',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'heavy_support'}, related_name='heavy_support', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='minroster',
            name='troops',
            field=models.ManyToManyField(limit_choices_to={'battlefield_role': 'troops'}, related_name='troop', to='wh_info.character'),
        ),
    ]
