# Generated by Django 4.0.6 on 2022-10-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0006_remove_minroster_com1_remove_minroster_com2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minroster',
            name='commanders',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='elites',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='fast_attacks',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='flyers',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='heavy_supports',
        ),
        migrations.RemoveField(
            model_name='minroster',
            name='troops',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='character',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='dedicated_transport',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='elite',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='fast_attack',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='heavy_support',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='lords_of_war',
        ),
        migrations.AddField(
            model_name='roster',
            name='commanders',
            field=models.ManyToManyField(limit_choices_to={'battlefield_role': 'commander'}, related_name='commander', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='roster',
            name='elites',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'elite'}, related_name='elite', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='roster',
            name='fast_attacks',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'fast_attack'}, related_name='fast_attack', to='wh_info.character'),
        ),
        migrations.AddField(
            model_name='roster',
            name='heavy_supports',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'heavy_support'}, related_name='heavy_support', to='wh_info.character'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='flyers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'battlefield_role': 'flyers'}, related_name='flyer', to='wh_info.character'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Roster name'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='troops',
            field=models.ManyToManyField(limit_choices_to={'battlefield_role': 'troops'}, related_name='troop', to='wh_info.character'),
        ),
        migrations.DeleteModel(
            name='Battalion',
        ),
        migrations.DeleteModel(
            name='MinRoster',
        ),
    ]
