# Generated by Django 4.0.6 on 2022-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0008_strategems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategems',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strategems',
            name='fraction',
            field=models.CharField(choices=[('imperium', 'Империум'), ('chaos', 'хаос'), ('xeno', 'ксеносы')], max_length=100),
        ),
        migrations.AlterField(
            model_name='strategems',
            name='type',
            field=models.CharField(choices=[('Battle_Tactic_Stratagem', 'Battle Tactic Stratagem'), ('Epic_Deed_Stratagem', 'Epic Deed Stratagem'), ('Requisition_Stratagem', 'Requisition Stratagem'), ('Strategic_Ploy_Stratagem', 'Strategic Ploy Stratagem'), ('Wargear_Stratagem', 'Wargear Stratagem')], max_length=100),
        ),
    ]
