# Generated by Django 4.0.6 on 2022-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0013_remove_character_keywors_character_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='troops',
            field=models.ManyToManyField(related_name='troop', to='wh_info.character'),
        ),
    ]
