# Generated by Django 4.0.6 on 2022-11-15 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0014_alter_roster_troops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cost',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='power_rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
