# Generated by Django 4.0.6 on 2022-11-22 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_info', '0015_alter_character_cost_alter_character_power_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cost',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
    ]
