# Generated by Django 4.0.6 on 2022-11-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wh_info', '0016_alter_character_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roster', to='users.profile', verbose_name='Пользователь'),
        ),
    ]
